---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-credentials
  namespace: kube-system
spec:
  encryptedData:
    api-token: AgBUckaTZqJ4+uJOPSzCYRjyhf8soS7tYx6rk0+7rEnei/QBoAkzxD656Siu0MW7dD/d6iV5wmrg3/8m7wYZFEmNauQ5COSaYds3Wu4uIKgHKiite5SK15uROlEdSCdnTYszwCfP4aFG+oPdPShIMqF5BgCeh3k6WCwrin/DJIajZ/3+FQ2FjTeBLbhq0acalYNQaDxX8lKCIEfCbjeIyPBI83A2MCaO7kKBzIQ1eAhYFm4zgW1i/THZ2lkqzyi+qFDcofqN9qOAUElEsxM9pyGqGE8drmBeMJ5pNt4eCXZQRywEuCmpu2HGwC1qSdOYKLbuf/l3ReKKR/0lOkpGWI7hZRniySpAty5Oq8mBoYsQQKCXjh0GcMFco8OpDOHNWdGMhvlOV6LK8cs2N4PYIc+ENKpKmJR7Jy319zmnmycY94nA0hCj4EmL5ROQcanf0UrrdEYir2z0MXWz8pbhh/9zahweQ7K68r2BEAWDnTGWabLqfzg7564VyvUMQbOYyiTPXBwBeItecI8ESeyFKAeuWIls9ViGUDXNtWUv5oCYqPQrw8KelwP201eCjKT/IYI5CCeuwLwHtmGEg/T4MIo2jpQeLZS6XqQE2+dUMXnkyiMnO7AvCQt9JROWT58AFmkWEL1rKLB7f69KS3AboFky3jAlALx7WMjLKTRMRvkgCgmYnojPYuA/5MSRCoWFHM8Vr53uucCfAkHMFYK0uJTYdEpQarH0cfKmRByHtwLqEDKq851jLRBRhCgBGh4QQKBPKK0UBw==
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-credentials
      namespace: kube-system
