---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgAB6lochwnnS+qG47jSSfNzbXLsD+3XWgJzc/R3LjGNapjnZPa3DgdQKS6AmNgt/RQMlPqPZbBesbDepY/UetgwnQX1yapRES8NCuDV6MUIVFrCjt4dnP6gpgw5fmGH4Anzjt7+f0k7S1Foqq3JjtW3VoiKt+9uhI87WejduQYVSqfnWcaulzM6k4+pCXwNW4AgemPbU85qT+AEDs8ga2QbHjz98xW12+Jg87FllUf+/QLVhZw8+/IwgruybLTF5Z5xVc2n67TkaVWH6ZKYXD/O7qnRe0RCLaN96xZYx6hd6PIN579QpHWlaQoGRp+qOuuJF+doaou2UsLmXBZ8LbF5qRXEiWudjOBB4PiWyljJKIjKjvYzYZSmeEb4SBKfte/I/+n4UmdjTu8QHhmWGFN3T1SiL7pwkQMnh19hcGmNOMqakIrV+pc9aHKmZlQXEqkRAVADV9YQfgrXLxbAdBH8bKejcljsKv16E8upFi+uFwnT75Ja1aAQcxs8PonegR5ghud6akFvMO3cgMJbcWhhcStatUspcN2QdRO3lyZcZQCq1qsACOO/wsje1TxGIwicrr2ZLK3lYWuDxVU4s0ZAmU0gucldUyFq4SPNcSdsVLxbL6n2NKM8paPJ1qDDNHGFnF8G++wtVPjOH/abUyHMg/d0AW5Fd32qTbWhZaLbG83ns/BZRmDg67zG+WWTaj7V44U10C0/Z1SjIgk8gSkitORlQM6hWBU8ExitwMWpdSaCm32aNbdB1ErLaZUbRknX3I8dEQ==
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token-secret
      namespace: cert-manager
