apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns
  namespace: kube-system
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: external-dns
  template:
    metadata:
      labels:
        app: external-dns
    spec:
      serviceAccountName: external-dns
      containers:
      - name: external-dns
        image: registry.k8s.io/external-dns/external-dns:v0.14.0
        args:
        - --source=ingress
        - --domain-filter=questhub.fr
        - --provider=ovh
        - --policy=upsert-only
        - --txt-owner-id=k3s-ovh-homelab
        - --target=82.67.198.156
        env:
        - name: OVH_APPLICATION_KEY
          valueFrom:
            secretKeyRef:
              name: ovh-credentials
              key: application-key
        - name: OVH_APPLICATION_SECRET
          valueFrom:
            secretKeyRef:
              name: ovh-credentials
              key: application-secret
        - name: OVH_CONSUMER_KEY
          valueFrom:
            secretKeyRef:
              name: ovh-credentials
              key: consumer-key
