name: Deploy Documentation to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
      - '.github/workflows/documentation.yml'

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Configure Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Cache MkDocs dependencies
        uses: actions/cache@v4
        with:
          key: ${{ github.ref }}
          path: .cache

      - name: Install dependencies
        run: |
          pip install mkdocs-material

      - name: Build and deploy to GitHub Pages
        run: mkdocs gh-deploy --force
